services:
  avro-editor:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - SERVER_ROOT=/var/public
      - SERVER_PORT=80
      - SERVER_COMPRESSION=true
      - SERVER_LOG_LEVEL=info
